### PR TITLE
Release 1.12.0

### PR DESCRIPTION
**Pull request by yshmatov-anaconda**

### CODE REVIEW

**Comment by AlbertDeFusco** [comment]
Hi! I'm curious, when this expected to be released?

**Comment by csoja** [comment]
It is currently in QA - hopefully next week to be released?  @vshevchenko-anaconda can you confirm and address Albert's other question?

**Comment by yshmatov-anaconda** [comment]
@AlbertDeFusco this change is included in this release. However - we also created a solution that also prefers CONDA_EXE, and which covers more cases (_including conda-less environments_).

It appears that we worked on both solutions at the same time, but we first included our solution in the `dev` branch (_where we collect new releases_), while this solution was for some reason merged into the `master` (_which should be the latest stable release_). We backported all changes from master, fixed conflicts, and merged them into a complete current solution. Thus we just have more compared to what we have in `master`.

**Comment by AlbertDeFusco** [comment]
Great!

**Pull request merged**
