### PR TITLE
Switch from anaconda_project to conda_kapsel API

### LINKED ISSUE #345: Port to conda-kapsel rather than anaconda_project

### PR DESCRIPTION
**Pull request by havocp**
fixes #345

### CODE REVIEW

**Comment by havocp** [comment]
Travis passed on linux-64. It failed on linux-32 because of a missing keyring package, which I've since added, but I'm not sure it works (or that it's needed) since the missing keyring would mean you can't install the optional conda-kapsel dependency on linux-32 and that's it. Pushing a gratuitous commit to kick the build might fix linux-32. I don't think windows/osx are going to pass because we don't have build workers for those, so not sure it's possible to make travis pass.

**Comment by bollwyvl** [comment]
I was just successfully able to build this (and conda-kapsel) locally and used them to upload a kapsel to my local dev server. LGTM! 👍

**Comment by havocp** [comment]
Anyone know what steps we've used to build releases of anaconda-client in the past? If it relied on the CI we may need a new plan. @srossross might know ?

**Comment by bollwyvl** [comment]
@goanpeca mentioned updating the CI to Cirleveyoravis yesterday...

But _we_ don't actually build releases, distribution team does...

**Pull request merged**
