### PR TITLE
Port project upload to anaconda-project API

### PR DESCRIPTION
**Pull request by havocp**
Currently this makes anaconda-project an optional runtime dependency (if you don't have it installed, it suggests installing it), to avoid circularity. However anaconda-project is required to run the tests (which is a bit awkward at the moment since there isn't a conda package with the needed APIs). This PR also requires the anaconda-project PR https://github.com/Anaconda-Platform/anaconda-project/pull/324

I'd like to get some review on this PR in case there are needed changes in https://github.com/Anaconda-Platform/anaconda-project/pull/324 as well; once we like the code in both PRs, I could merge the project PR, make a conda package of anaconda-project, and then we could merge this one.

For background please see https://github.com/Anaconda-Platform/anaconda-client/issues/324
Note, very confusingly and by coincidence, that https://github.com/Anaconda-Platform/anaconda-project/pull/324 is the project PR this PR depends on, and https://github.com/Anaconda-Platform/anaconda-client/issues/324 is the client issue with background discussion, they have the same number.

### CODE REVIEW

**Comment by havocp** [comment]
The CI is failing due to the missing dependency. Once people think the PRs look good I'll publish anaconda-project and update the CI deps.

**Comment by havocp** [comment]
Hmm. The anaconda_project conda package is private so the CI can't install it... not sure how to solve.

**Comment by mmarchetti** [comment]
You can use a channel token like this example: https://github.com/Anaconda-Platform/anaconda-server/blob/develop/.binstar.yml#L16

**Comment by havocp** [comment]
conda broken on Windows?
```
An unexpected error has occurred, please consider sending the

following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):

  File "C:\Users\binstar\conda-build-miniconda\Scripts\conda-build-script.py", line 4, in <module>

    sys.exit(main())

  File "C:\Users\binstar\conda-build-miniconda\lib\site-packages\conda_build\main_build.py", line 208, in main

    args_func(args, p)

  File "C:\Users\binstar\conda-build-miniconda\lib\site-packages\conda_build\main_build.py", line 493, in args_func

    args.func(args, p)

  File "C:\Users\binstar\conda-build-miniconda\lib\site-packages\conda_build\main_build.py", line 438, in execute

    include_recipe=args.include_recipe)

  File "C:\Users\binstar\conda-build-miniconda\lib\site-packages\conda_build\build.py", line 477, in build

    windows.build(m, build_file)

  File "C:\Users\binstar\conda-build-miniconda\lib\site-packages\conda_build\windows.py", line 204, in build

    kill_processes()

  File "C:\Users\binstar\conda-build-miniconda\lib\site-packages\conda_build\windows.py", line 157, in kill_processes

    import psutil

ImportError: No module named 'psutil'
```

**Comment by havocp** [comment]
With https://github.com/Anaconda-Platform/anaconda-project/pull/326 we could easily move the uploader code back to anaconda-client, which is probably logical. Then changes to the server API could all be adapted to inside anaconda-client.

**Comment by havocp** [comment]
ok now anaconda-project doesn't work on py2/win32, so working on that back over on a-p

**Pull request merged**
