### PR TITLE
AC-208: fix uploads of existing packages

### PR DESCRIPTION
**Pull request by yshmatov-anaconda**

### CODE REVIEW

**Review by vshevchenko-anaconda — APPROVED** [review]

**Comment by matthewfeickert** [comment]
@yshmatov-anaconda @vshevchenko-anaconda is this related to Issue https://github.com/Anaconda-Platform/anaconda-client/issues/702 at all? Or is this for a seperate problem?

**Comment by matthewfeickert** [comment]
> It should fix the https://github.com/Anaconda-Platform/anaconda-client/issues/702.

Great.

> We should have a 1.12.3 released soon with this fix included.

Yes, I'm watching https://github.com/conda-forge/anaconda-client-feedstock/pull/52. Here's hoping that gets released today.

**Comment by mbargull** [comment]
> Yes, I'm watching [conda-forge/anaconda-client-feedstock#52](https://github.com/conda-forge/anaconda-client-feedstock/pull/52). Here's hoping that gets released today.

Since we had an issue with the CI not running for `conda-forge::anaconda-client=1.12.2`, I'll monitor the build closely so we do indeed get it in now ;).

**Comment by matthewfeickert** [comment]
> Since we had an issue with the CI not running for conda-forge::anaconda-client=1.12.2, I'll monitor the build closely so we do indeed get it in now ;).

Thanks very much @mbargull! 

And thank you again @yshmatov-anaconda as having `anaconda-client` `v1.12.3` out is very nice!

**Pull request merged**
